name: epp_user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.7
  http_parser: ^4.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  mime: ^1.0.0
  permission_handler: ^11.3.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600

    - family: EbGaramond
      fonts:
        - asset: assets/fonts/EBGaramond-Bold.ttf
        - asset: assets/fonts/EBGaramond-Regular.ttf
          weight: 400

